# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  lambda-client-benchmarks:
    dependencies:
    - base
    - lambda-client
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: lambda-client is a new Haskeleton package.
dependencies:
  - classy-prelude
executables:
  lambda-client:
    dependencies:
    - base
    - lambda-client
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/lambda-client
library:
  default-extensions:
    - NoImplicitPrelude
    - GADTs
    - TypeFamilies
    - OverloadedStrings
    - QuasiQuotes
    - MultiParamTypeClasses
    - GeneralizedNewtypeDeriving
  dependencies:
    - base
    - lambda-protocol
    - lambda-prelude
    - lambda-bus
    - lambda-logger
    - connection
    - cereal
  source-dirs: library
license: MIT
maintainer: Yorick Laupa
name: lambda-client
synopsis: A new Haskeleton package.
tests:
  lambda-client-test-suite:
    dependencies:
    - base
    - lambda-client
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
