# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  lambda-node-benchmarks:
    dependencies:
    - base
    - lambda-node
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: lambda-node is a new Haskeleton package.
executables:
  lambda-node:
    dependencies:
    - base
    - lambda-node
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
dependencies:
  - classy-prelude
  - optparse-applicative
  - monad-logger
  - fast-logger
  - ekg
  - ekg-core
  - uuid
  - lambda-prelude
  - lambda-logger
  - lambda-bus
  - connection
  - operational
default-extensions:
  - NoImplicitPrelude
  - LambdaCase
  - OverloadedStrings
  - TypeFamilies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - FlexibleContexts
  - QuasiQuotes
  - RecordWildCards
  - DeriveGeneric
  - RankNTypes
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/lambda-node
library:
  dependencies:
  - base
  - network
  - clock
  - network-simple
  - lambda-protocol
  - cereal
  - time
  - pretty
  - aeson
  - machines
  - resourcet
  source-dirs: library
license: MIT
maintainer: Yorick Laupa
name: lambda-node
synopsis: A new Haskeleton package.
tests:
  lambda-node-test-suite:
    dependencies:
    - base
    - lambda-node
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
