# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Other
description: lambda-protocol is a new Haskeleton package.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/lambda-protocol
library:
  default-extensions:
    - NoImplicitPrelude
    - GeneralizedNewtypeDeriving
  dependencies:
    - base >=4.9 && <5
    - protobuf
    - classy-prelude
    - uuid
    - cereal
    - hashable
  source-dirs: library
license: MIT
maintainer: Yorick Laupa
name: lambda-protocol
synopsis: A new Haskeleton package.
tests:
  lambda-protocol-test-suite:
    dependencies:
    - base
    - lambda-protocol
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
