# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  lambda-server-benchmarks:
    dependencies:
    - base
    - lambda-server
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: lambda-server is a new Haskeleton package.
executables:
  lambda-server:
    default-extensions:
      - NoImplicitPrelude
    dependencies:
    - base
    - lambda-server
    - optparse-applicative
    - classy-prelude
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/lambda-server
library:
  default-extensions:
    - NoImplicitPrelude
  dependencies:
    - base
    - classy-prelude
    - lambda-protocol
    - connection
    - network
    - uuid
    - cereal
  source-dirs: library
license: MIT
maintainer: Yorick Laupa
name: lambda-server
synopsis: A new Haskeleton package.
tests:
  lambda-server-test-suite:
    dependencies:
    - base
    - lambda-server
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
